# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Updated to latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=500']  # Set specific file size limit
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']  # Avoid false positives
      - id: check-yaml  # Added YAML validation
      - id: check-merge-conflict  # Added merge conflict detection
      - id: check-json  # Added JSON validation
      - id: check-toml  # Added TOML validation
      - id: detect-private-key  # Added private key detection
      - id: mixed-line-ending
        args: ['--fix=lf']  # Ensure consistent line endings
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.0  # Updated to latest stable version
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        args:
          - --tf-init-args=-upgrade  # Ensure latest provider versions
      - id: terraform_tfsec
        args:
          - --args=--format json --exclude-downloaded-modules
  - repo: https://github.com/crate-ci/typos
    rev: v1.16.23
    hooks:
      - id: typos
        types: [markdown]
        args: ['--format', 'brief']
        exclude: 'CHANGELOG.md'

  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.2.0
    hooks:
      - id: checkov
        args: [--framework, terraform, --skip-check, CKV_AWS_117]  # Skip Lambda DLQ check for Cognito module
