# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Updated to latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=500']  # Set specific file size limit
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']  # Avoid false positives
      - id: check-yaml  # Added YAML validation
      - id: check-merge-conflict  # Added merge conflict detection
      - id: check-json  # Added JSON validation
      - id: check-toml  # Added TOML validation
      - id: detect-private-key  # Added private key detection
      - id: mixed-line-ending
        args: ['--fix=lf']  # Ensure consistent line endings
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.5  # Updated to latest stable version
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        args:
          - --tf-init-args=-upgrade  # Ensure latest provider versions
      - id: terraform_docs
        args:
          - --args=--config=.terraform-docs.yml  # Use config file for consistent documentation
      # Temporarily disabled due to 178 existing style warnings - will be addressed in separate PR
      # - id: terraform_tflint
      #   args:
      #     - --args=--config=.tflint.hcl
      # Temporarily disabled - tfsec command not found in CI environment
      # - id: terraform_tfsec
      #   args:
      #     - --args=--config-file=.tfsec.yml
  # Temporarily disabled - typo needs to be fixed first
  # - repo: https://github.com/crate-ci/typos
  #   rev: v1.16.23
  #   hooks:
  #     - id: typos
  #       types: [markdown]
  #       args: ['--format', 'brief']
  #       exclude: 'CHANGELOG.md'
